const ADD = 'ADD',
  DELETE = 'DELETE',
  UPDATE = 'UPDATE',
  UPLOAD = 'UPLOAD',
  USERS = 'users',
  ADDPRODUCT = 'ADDPRODUCT',
  UPDATE_INVENTORY_BOUGHT = 'UPDATE_INVENTORY_BOUGHT',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART',
  SETACTIVE = 'SETACTIVE';

export { ADD, DELETE, UPDATE, UPLOAD, USERS, UPDATE_INVENTORY_BOUGHT, ADDPRODUCT, REMOVE_FROM_CART, SETACTIVE };
